unpackaged/main/default/objects/Asunto__c/Asunto__c.object-meta.xml
<CustomObject>
    <description>Listado de Asuntos</description>
    <label>Asunto</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Nombre de Asunto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asuntos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asunto__c/fields/Abogado_Externo__c.field-meta.xml
<CustomField>
    <fullName>Abogado_Externo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abogado Externo</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asuntos (Abogado Externo)</relationshipLabel>
    <relationshipName>Asuntos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Abogado_Interno__c.field-meta.xml
<CustomField>
    <fullName>Abogado_Interno__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abogado Interno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asuntos</relationshipLabel>
    <relationshipName>Asuntos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Acreditado__c</fullName>
    <label>NOMBRE DEL DEMANDADO</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Codigo_de_Resultado_RO__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Resultado_RO__c</fullName>
    <label>Codigo de Resultado Actual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial_RO__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial_RO__c</fullName>
    <label>Etapa Judicial Actual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AsuntosPorAEController.cls
public with sharing class AsuntosPorAEController {

	public String aeID {get; set;}
	public List<Asunto__c> losAsuntos {get; set;}

	public AsuntosPorAEController() {
		aeID = apexpages.currentpage().getparameters().get('AEID');
		if(aeID == null)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No se encontro al Abogado Externo en el Sistema.'));
			losAsuntos = new List<Asunto__c>();
		}
		else
		{
			losAsuntos = [SELECT Id, 
								Abogado_Externo__c,
								Abogado_Interno__c, 
								Acreditado__c, 
								Etapa_Judicial_RO__c, 
								Codigo_de_Resultado_RO__c
								FROM Asunto__c 
								WHERE Abogado_Externo__c =: aeID ];
		}
	}
}