unpackaged/main/default/objects/Asunto__c/Asunto__c.object-meta.xml
<CustomObject>
    <description>Listado de Asuntos</description>
    <label>Asunto</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Nombre de Asunto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asuntos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asunto__c/fields/Abogado_Interno__c.field-meta.xml
<CustomField>
    <fullName>Abogado_Interno__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abogado Interno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asuntos</relationshipLabel>
    <relationshipName>Asuntos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Acreditado__c</fullName>
    <label>NOMBRE DEL DEMANDADO</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Direcci_n_o_Filial__c.field-meta.xml
<CustomField>
    <fullName>Direcci_n_o_Filial__c</fullName>
    <label>Dirección o Filial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Almacenadora</fullName>
            </value>
            <value>
                <fullName>Arrendadora</fullName>
            </value>
            <value>
                <fullName>Auto Plazo</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Factoraje</fullName>
            </value>
            <value>
                <fullName>Hipotecario</fullName>
            </value>
            <value>
                <fullName>Hombre Camion</fullName>
            </value>
            <value>
                <fullName>Nomina</fullName>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor y localizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y emplazan por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Fecha_de_Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Ingreso__c</fullName>
    <label>Fecha de Ingreso</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>Sucursal__c</referenceTo>
    <relationshipLabel>Asuntos</relationshipLabel>
    <relationshipName>Asuntos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/Etapa_Judicial__c.object-meta.xml
<CustomObject>
    <label>Etapa Judicial</label>
    <nameField>
        <displayFormat>EJ-{00000000}</displayFormat>
        <label>Nombre de Etapa Judicial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Etapas Judiciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Etapas Judiciales</relationshipLabel>
    <relationshipName>Etapas_Judiciales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor ilocalizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y Emplazam. por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Apelación</fullName>
            </value>
            <value>
                <fullName>Amparo directo</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
            <value>
                <fullName>Para Dictamen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Fecha_de_Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Etapa_Judicial__c</fullName>
    <label>Fecha de Etapa Judicial</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sucursal__c/Sucursal__c.object-meta.xml
<CustomObject>
    <label>Sucursal</label>
    <nameField>
        <label>Nombre de Sucursal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sucursal__c/fields/Ciudad2__c.field-meta.xml
<CustomField>
    <fullName>Ciudad2__c</fullName>
    <label>Ciudad</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ERGDataFactory.cls
public with sharing class ERGDataFactory {

	// ------------------ ACCOUNT METHODS ------------------------

	public static List<Account> createAccounts(Integer pNumber)
	{
		List<Account> accountsToCreate = new List<Account>(); 

		if(pNumber <= 0) return accountsToCreate; 

		for(Integer i = 0; i < pNumber; i++)
		{
			Account newAccount = new Account(Name = 'Name'+i); 
			accountsToCreate.add(newAccount);
		}

		insert accountsToCreate;

		return accountsToCreate;
	}

	// ------------------ CONTACTS METHODS ------------------------

	public static List<Contact> createContacts(Integer pNumber, Id pAccountId)
	{
		List<Contact> theContactsToCreate = new List<Contact>(); 

		for(Integer i = 0; i < pNumber; i++)
		{
			Contact aContact = new Contact(); 
			aContact.FirstName = 'FirstName'+i;
			aContact.LastName = 'LastName'+i;
			aContact.Email = 'test'+i+'@testContact.com';
			aContact.AccountId = pAccountId;
			theContactsToCreate.add(aContact);
		}

		if(!theContactsToCreate.isEmpty())
		{
			insert theContactsToCreate;
		}

		return theContactsToCreate;
	}
	
	public static List<Sucursal__c> createSucursales(Integer pNumber)
	{
		List<Sucursal__c> sucursalesToCreate = new List<Sucursal__c>(); 

		for(Integer i = 0; i < pNumber; i++)
		{
			Sucursal__c aSucursal = new Sucursal__c(); 
			aSucursal.Name = 'Sucursal'+i;
			aSucursal.Ciudad2__c = 'Ciudad'+i;
			sucursalesToCreate.add(aSucursal);
		}

		if(!sucursalesToCreate.isEmpty())
		{
			insert sucursalesToCreate;
		}

		return sucursalesToCreate;
	}

	public static List<Asunto__c> createAsuntos(Integer pNumber)
	{
		List<Asunto__c> asuntosToCreate = new List<Asunto__c>();
		List<Account> accountAbogados = ERGDataFactory.createAccounts(1);
		List<Contact> abogadoInternos = ERGDataFactory.createContacts(1, accountAbogados[0].Id); 
		List<Sucursal__c> sucursales = ERGDataFactory.createSucursales(1); 
		
		for(Integer i = 0; i < pNumber; i++)
		{
			Asunto__c anAsunto = new Asunto__c(); 
			anAsunto.Fecha_de_Ingreso__c = System.today(); 
			anAsunto.Acreditado__c = 'Acreditado'+i;
			anAsunto.Abogado_Interno__c = abogadoInternos[0].Id;
			anAsunto.Direcci_n_o_Filial__c = 'Comercial';
			anAsunto.Sucursal__c = sucursales[0].Id;
			asuntosToCreate.add(anAsunto);
		}

		if(!asuntosToCreate.isEmpty())
		{
			insert asuntosToCreate;
		}

		return asuntosToCreate;
	}
	
	public static Etapa_Judicial__c addEtapaJudicial(Id asuntoId, String etapaName, Date fecha)
	{
		Etapa_Judicial__c theEtapa = new Etapa_Judicial__c(); 
		theEtapa.Asunto__c = asuntoId; 
		theEtapa.Etapa_Judicial__c = etapaName; 
		theEtapa.Fecha_de_Etapa_Judicial__c = fecha; 
		insert theEtapa; 
		return theEtapa; 
	}
}