unpackaged/main/default/objects/Asunto__c/Asunto__c.object-meta.xml
<CustomObject>
    <description>Listado de Asuntos</description>
    <label>Asunto</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Nombre de Asunto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asuntos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asunto__c/fields/Deudores_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Deudores_Importe_Only__c</fullName>
    <label>Deudores Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor y localizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y emplazan por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial_Importe_Only__c</fullName>
    <label>Etapa Judicial Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/MONTO__c.field-meta.xml
<CustomField>
    <fullName>MONTO__c</fullName>
    <label>MONTO</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Monto_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Monto_Importe_Only__c</fullName>
    <label>Monto Importe Only</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/NDC_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>NDC_Importe_Only__c</fullName>
    <label>NDC Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Nivel_de_Etapa__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_Etapa__c</fullName>
    <label>Nivel de Etapa</label>
    <summarizedField>Etapa_Judicial__c.Nivel_de_Etapa__c</summarizedField>
    <summaryForeignKey>Etapa_Judicial__c.Asunto__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/Etapa_Judicial__c.object-meta.xml
<CustomObject>
    <label>Etapa Judicial</label>
    <nameField>
        <displayFormat>EJ-{00000000}</displayFormat>
        <label>Nombre de Etapa Judicial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Etapas Judiciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Etapas Judiciales</relationshipLabel>
    <relationshipName>Etapas_Judiciales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor ilocalizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y Emplazam. por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Apelación</fullName>
            </value>
            <value>
                <fullName>Amparo directo</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
            <value>
                <fullName>Para Dictamen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Fecha_de_Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Etapa_Judicial__c</fullName>
    <label>Fecha de Etapa Judicial</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Nivel_de_Etapa__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_Etapa__c</fullName>
    <formula>IF( ISPICKVAL( Etapa_Judicial__c , 'Demanda'),1,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Notificación y emplazamiento personal en trámite'),2,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Deudor ilocalizado en emplazamiento'),3,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Not. y Emplazam. por edictos en tramite'),4,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Notificacion y emplazamiento personal en tramite'),2,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Contestación a la demanda'),5,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Contestacion a la Demanda'),5,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Embargo antes de Sentencia'),6,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Pruebas'),7,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Solicitud se dicte sentencia definitiva'),8,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Se solicita se dicte sentencia definitiva'),8,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Apelación'),9,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Apelacion'),9,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Amparo directo'),10,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Amparo'),10,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Ejecución de Sentencia'),11,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Ejecucion de Sentencia'),11,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Ejecución de Convenio'),12,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Ejecucion de Convenio'),12,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Remate de Bienes'),13,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Audiencia de Remate'),14,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Escrituración en Trámite'),15,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Escrituracion en Tramite'),15,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Escrituras en Tramite'),15,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Toma posesión bien adjudicado y/o arrendado'),16,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Incidente / Tercería'),17,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Cierre de Juicio'),18,
    IF(ISPICKVAL( Etapa_Judicial__c , 'Para Dictamen'),19,0
    ))))))))))))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nivel de Etapa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/Numero_de_Credito__c.object-meta.xml
<CustomObject>
    <label>Numero de Credito</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Nombre de Numero de Credito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Numeros de Credito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Numeros de Credito</relationshipLabel>
    <relationshipName>Numeros_de_Credito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Monto__c.field-meta.xml
<CustomField>
    <fullName>Monto__c</fullName>
    <label>Monto</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Numero_de_Credito__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Credito__c</fullName>
    <label>NÚMERO DE CRÉDITO</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Terceros_Obligados__c.field-meta.xml
<CustomField>
    <fullName>Terceros_Obligados__c</fullName>
    <label>Terceros Obligados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SECAL_App__c/SECAL_App__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SECAL App</label>
</CustomObject>

unpackaged/main/default/objects/SECAL_App__c/fields/Crear_Etapas_Judiciales_en_Importe__c.field-meta.xml
<CustomField>
    <fullName>Crear_Etapas_Judiciales_en_Importe__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activa la creacion automatica de etapas judiciales en importe</inlineHelpText>
    <label>Crear Etapas Judiciales en Importe</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SECAL_App__c/fields/Crear_Numeros_de_Credito_en_Importe__c.field-meta.xml
<CustomField>
    <fullName>Crear_Numeros_de_Credito_en_Importe__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activa la creacion automatica de numero de creditos en importe</inlineHelpText>
    <label>Crear Numeros de Credito en Importe</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AsuntosService.cls
public with sharing class AsuntosService {
	
	public static boolean  triggerOnAsuntosHasExecuted = false;
	public static boolean triggerOnEtapaJudicialHasExecuted = false; 

	public static SECAL_App__c appSettings; 

	public static Map<ID,Etapa_Judicial__c> getMapAsuntoToEtapaJudicial(List<Etapa_Judicial__c> pEtapasJudiciales)
	{
		Map<ID,Etapa_Judicial__c> mapAsuntoIdToEtapaJudicial = new Map<ID,Etapa_Judicial__c>(); 

		if(pEtapasJudiciales != null && !pEtapasJudiciales.isEmpty())
		{
			for(Etapa_Judicial__c etapa: pEtapasJudiciales)
			{
				Etapa_Judicial__c theEtapa = mapAsuntoIdToEtapaJudicial.get(etapa.Asunto__c); 
				if(theEtapa == null)
				{
					mapAsuntoIdToEtapaJudicial.put(etapa.Asunto__c, etapa);
				}
				else
				{
					if(theEtapa.Fecha_de_Etapa_Judicial__c < etapa.Fecha_de_Etapa_Judicial__c)
					{
						mapAsuntoIdToEtapaJudicial.put(etapa.Asunto__c, etapa);
					}
					if(theEtapa.Fecha_de_Etapa_Judicial__c == etapa.Fecha_de_Etapa_Judicial__c)
					{
						if(theEtapa.Nivel_de_Etapa__c < etapa.Nivel_de_Etapa__c)
						{
							mapAsuntoIdToEtapaJudicial.put(etapa.Asunto__c, etapa);
						}
						if(theEtapa.Nivel_de_Etapa__c == etapa.Nivel_de_Etapa__c)
						{
							if(theEtapa.CreatedDate < etapa.CreatedDate)
							{
								mapAsuntoIdToEtapaJudicial.put(etapa.Asunto__c, etapa);
							}
						}
					}
				}
			}
		}
		return mapAsuntoIdToEtapaJudicial;
	}

	public static List<Numero_de_Credito__c> createNumerosDeCredito(List<Asunto__c> asuntos)
	{
		List<Numero_de_Credito__c> numerosDeCredito = new List<Numero_de_Credito__c>();

		for(Asunto__c asunto: asuntos)
		{
			System.debug('Adding Credit for Asunto: '+asunto);
			List<String> numerosDeCreditoString = new List<String>(); 
			if(asunto.NDC_Importe_Only__c != null) numerosDeCreditoString = asunto.NDC_Importe_Only__c.split(',');
			for(Integer i = 0; i < numerosDeCreditoString.size(); i++)
			{
				System.debug('Adding Credit :'+numerosDeCreditoString[i]);
				Numero_de_Credito__c newNC = new Numero_de_Credito__c(); 
				newNC.Numero_de_Credito__c = numerosDeCreditoString[i]; 
				newNC.Asunto__c = asunto.Id; 
				newNC.Monto__c = 0;
				if(i == 0)
				{
					newNC.Monto__c = asunto.Monto_Importe_Only__c; 
					newNC.Terceros_Obligados__c = asunto.Deudores_Importe_Only__c; 
				}
				numerosDeCredito.add(newNC);
			}
		}
		if(!numerosDeCredito.isEmpty()) insert numerosDeCredito;
		return numerosDeCredito;
	}

	public static List<Etapa_Judicial__c> createEtapaJudicial(List<Asunto__c> asuntos)
	{
		List<Etapa_Judicial__c> etapasJudiciales = new List<Etapa_Judicial__c>(); 
		for(Asunto__c asunto: asuntos)
		{
			Etapa_Judicial__c etapaJudicial = new Etapa_Judicial__c();
			etapaJudicial.Fecha_de_Etapa_Judicial__c = Date.newInstance(2016,3,9); 
			etapaJudicial.Etapa_Judicial__c = asunto.Etapa_Judicial_Importe_Only__c; 
			etapaJudicial.Asunto__c = asunto.Id;
			etapasJudiciales.add(etapaJudicial);
		}
		if(!etapasJudiciales.isEmpty()) insert etapasJudiciales;
		return etapasJudiciales;
	}

	public static Boolean createNumerosDeCreditoIsEnabled()
	{
		if(appSettings == null)
		{
			appSettings = SECAL_App__c.getOrgDefaults();
		}

		return appSettings.Crear_Numeros_de_Credito_en_Importe__c; 
	}

	public static Boolean createEtapaJudicialIsEnabled()
	{
		if(appSettings == null)
		{
			appSettings = SECAL_App__c.getOrgDefaults();
		}

		return appSettings.Crear_Etapas_Judiciales_en_Importe__c; 
	}

	public static void updateEtapasJudicialesAndCodigos(List<Etapa_Judicial__c> etapasList)
	{
		Map<Id,Etapa_Judicial__c> mapAsuntoIdToEtapaJudicial = new Map<Id,Etapa_Judicial__c>();
		Set<Id> allAsuntosIds = new Set<Id>();
		for(Etapa_Judicial__c etapa: etapasList)
		{
			allAsuntosIds.add(etapa.Asunto__c);
		}

		List<Etapa_Judicial__c> allEtapasJuridicas = [SELECT Id, Codigo_de_Resultado__c, Etapa_Judicial__c, Fecha_de_Etapa_Judicial__c, Nivel_de_Etapa__c, Asunto__c, CreatedDate FROM Etapa_Judicial__c WHERE Asunto__c IN: allAsuntosIds ORDER BY Fecha_de_Etapa_Judicial__c DESC];

		mapAsuntoIdToEtapaJudicial = AsuntosService.getMapAsuntoToEtapaJudicial(allEtapasJuridicas);
		
		List<Asunto__c> allAsuntos = [SELECT Id, Etapa_Judicial_RO__c, Codigo_de_Resultado_RO__c FROM Asunto__c WHERE Id IN: mapAsuntoIdToEtapaJudicial.keySet()]; 
		List<Asunto__c> asuntosToUpdate = new List<Asunto__c>();
		for(Asunto__c asunto: allAsuntos)
		{
			if(mapAsuntoIdToEtapaJudicial.get(asunto.Id) != null)
			{
				asunto.Etapa_Judicial_RO__c = mapAsuntoIdToEtapaJudicial.get(asunto.Id).Etapa_Judicial__c;
				asunto.Codigo_de_Resultado_RO__c = mapAsuntoIdToEtapaJudicial.get(asunto.Id).Codigo_de_Resultado__c;
				asuntosToUpdate.add(asunto);
			}
		}
		if(!asuntosToUpdate.isEmpty())
		{
			update asuntosToUpdate;
		}
	}
}