unpackaged/main/default/objects/Asunto__c/Asunto__c.object-meta.xml
<CustomObject>
    <description>Listado de Asuntos</description>
    <label>Asunto</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Nombre de Asunto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asuntos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor y localizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y emplazan por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Fecha_de_Asignacion_AE__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Asignacion_AE__c</fullName>
    <label>FECHA DE TRASPASO A EXTERNO</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/Etapa_Judicial__c.object-meta.xml
<CustomObject>
    <label>Etapa Judicial</label>
    <nameField>
        <displayFormat>EJ-{00000000}</displayFormat>
        <label>Nombre de Etapa Judicial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Etapas Judiciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Etapas Judiciales</relationshipLabel>
    <relationshipName>Etapas_Judiciales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor ilocalizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y Emplazam. por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Apelación</fullName>
            </value>
            <value>
                <fullName>Amparo directo</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
            <value>
                <fullName>Para Dictamen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Fecha_de_Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Etapa_Judicial__c</fullName>
    <label>Fecha de Etapa Judicial</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/AsuntosTimelineController.cls
public with sharing class AsuntosTimelineController {
    
    private final sObject mysObject;
    public ERGGoogleChartsTimelineSeq timelineData {get; set;}
    public Boolean timelineHasData {get; set;}
    public AsuntosTimelineController(ApexPages.StandardController stdController)
    {
        this.mysObject = (sObject)stdController.getRecord();
        List<Asunto__c> elAsunto = [SELECT Id, Fecha_de_Asignacion_AE__c, Name FROM Asunto__c WHERE Id =: this.mysObject.Id LIMIT 1];
        
        List<Etapa_Judicial__c> etapas = [SELECT Id, Etapa_Judicial__c, Fecha_de_Etapa_Judicial__c FROM Etapa_Judicial__c WHERE Asunto__c =: elAsunto[0].Id ORDER BY Fecha_de_Etapa_Judicial__c ASC];
        Map<String,String> columns = new Map<String,String>(); 
        columns.put('Main', 'Main'); 
        columns.put('Label', 'Etapa_Judicial__c'); 
        columns.put('Start', 'Fecha_de_Etapa_Judicial__c'); 
        columns.put('End','End');
        timelineData = new ERGGoogleChartsTimelineSeq((List<SObject>) etapas, Etapa_Judicial__c.SObjectType, columns, elAsunto[0].Fecha_de_Asignacion_AE__c, 'Asignacion a AE', elAsunto[0].Name);
    
        timelineHasData = !timelineData.rows.isEmpty();
    }
}