unpackaged/main/default/objects/Asunto__c/Asunto__c.object-meta.xml
<CustomObject>
    <description>Listado de Asuntos</description>
    <label>Asunto</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Nombre de Asunto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asuntos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asunto__c/fields/Codigo_de_Resultado_RO__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Resultado_RO__c</fullName>
    <label>Codigo de Resultado Actual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Deudores_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Deudores_Importe_Only__c</fullName>
    <label>Deudores Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor y localizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y emplazan por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial_Importe_Only__c</fullName>
    <label>Etapa Judicial Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial_RO__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial_RO__c</fullName>
    <label>Etapa Judicial Actual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/MONTO__c.field-meta.xml
<CustomField>
    <fullName>MONTO__c</fullName>
    <label>MONTO</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Monto_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Monto_Importe_Only__c</fullName>
    <label>Monto Importe Only</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/NDC_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>NDC_Importe_Only__c</fullName>
    <label>NDC Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/Etapa_Judicial__c.object-meta.xml
<CustomObject>
    <label>Etapa Judicial</label>
    <nameField>
        <displayFormat>EJ-{00000000}</displayFormat>
        <label>Nombre de Etapa Judicial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Etapas Judiciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Etapas Judiciales</relationshipLabel>
    <relationshipName>Etapas_Judiciales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Codigo_de_Resultado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Resultado__c</fullName>
    <label>Código de Resultado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etapa_Judicial__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 - Asignación a Externo</fullName>
                <label>10 - Enviada a Corresponsal</label>
            </value>
            <value>
                <fullName>AD - Rechazo de la demanda</fullName>
            </value>
            <value>
                <fullName>20 - Aclaración de la demanda</fullName>
                <label>20 - Presentada en Oficialía de Partes</label>
            </value>
            <value>
                <fullName>4A - Prevención para admisión de la demanda</fullName>
            </value>
            <value>
                <fullName>5A - Desahogo Prev. para admisión de demanda</fullName>
            </value>
            <value>
                <fullName>6A - Pendiente radicación de la demanda</fullName>
            </value>
            <value>
                <fullName>7A - Incompetencia del Juez</fullName>
            </value>
            <value>
                <fullName>8A - Demanda Admitida</fullName>
            </value>
            <value>
                <fullName>9A - Desechamiento de la de la demanda</fullName>
            </value>
            <value>
                <fullName>0A - Instructivo en Elaboración</fullName>
            </value>
            <value>
                <fullName>1B - Despecho / Exhorto Elabora y Presenta</fullName>
            </value>
            <value>
                <fullName>2B - Despacho / Exhorto Dilig. - Devolución</fullName>
            </value>
            <value>
                <fullName>3B - Desig. Actuario / Not. Encarga Actuario</fullName>
            </value>
            <value>
                <fullName>4B - Cita para Realizar Emplazamiento</fullName>
            </value>
            <value>
                <fullName>5B - Diligencia de Emplazamiento</fullName>
            </value>
            <value>
                <fullName>6B - Diligencia no Realizada</fullName>
            </value>
            <value>
                <fullName>7B - DNR por Inasistencia de Funcionario</fullName>
            </value>
            <value>
                <fullName>8B - DNR por no Encontrarse Persona Alguna</fullName>
            </value>
            <value>
                <fullName>9B - DNR por no ser Domicilio del Demandado</fullName>
            </value>
            <value>
                <fullName>0B - DNR por haber solo Menores de Edad</fullName>
            </value>
            <value>
                <fullName>30 - DNR por Negarse a Recibir Notificación</fullName>
            </value>
            <value>
                <fullName>40 - Emplazamiento Parcial</fullName>
            </value>
            <value>
                <fullName>3C - Autoriza Días/Horas Inhábil x Emplazar</fullName>
            </value>
            <value>
                <fullName>4C - Se Señala Nuevo Domicilio para Emplazar</fullName>
            </value>
            <value>
                <fullName>5C - Notificación y Emplazamiento Efectuado</fullName>
            </value>
            <value>
                <fullName>6C - Solicita Pesquisas Autoridades</fullName>
            </value>
            <value>
                <fullName>7C - Obtención de Oficios x Pesquisas</fullName>
            </value>
            <value>
                <fullName>8C - Presenta Oficios Pesquisas/se Razonan</fullName>
            </value>
            <value>
                <fullName>9C - Respuesta a Oficio de Localización</fullName>
            </value>
            <value>
                <fullName>0C - Ilocalizada No Emplazada / No Litis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor ilocalizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y Emplazam. por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Apelación</fullName>
            </value>
            <value>
                <fullName>Amparo directo</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
            <value>
                <fullName>Para Dictamen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/Numero_de_Credito__c.object-meta.xml
<CustomObject>
    <label>Numero de Credito</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Nombre de Numero de Credito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Numeros de Credito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Numeros de Credito</relationshipLabel>
    <relationshipName>Numeros_de_Credito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Monto__c.field-meta.xml
<CustomField>
    <fullName>Monto__c</fullName>
    <label>Monto</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Numero_de_Credito__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Credito__c</fullName>
    <label>NÚMERO DE CRÉDITO</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Numero_de_Credito__c/fields/Terceros_Obligados__c.field-meta.xml
<CustomField>
    <fullName>Terceros_Obligados__c</fullName>
    <label>Terceros Obligados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SECAL_App__c/SECAL_App__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SECAL App</label>
</CustomObject>

unpackaged/main/default/classes/OnAsuntoTrigger_Test.cls
@isTest
private class OnAsuntoTrigger_Test {
	
	@isTest static void should_update_etapa_judicial() {
		// Implement test code
		Asunto__c theAsunto = Test_DataFactory.createOneAsunto();
		AsuntosService.triggerOnAsuntosHasExecuted = false;
		Etapa_Judicial__c asignacionAExterno = Test_DataFactory.createAsignacionAExternoEtapa(theAsunto.Id);
		Asunto__c testAsunto = [SELECT Id, Etapa_Judicial_RO__c, Codigo_de_Resultado_RO__c FROM Asunto__c WHERE Id =: theAsunto.Id];
		System.assertEquals(testAsunto.Etapa_Judicial_RO__c, asignacionAExterno.Etapa_Judicial__c);
		System.assertEquals(testAsunto.Codigo_de_Resultado_RO__c, asignacionAExterno.Codigo_de_Resultado__c);
	}
	/*
	@isTest static void should_create_numero_de_credito() {
		// Implement test code
		SECAL_App__c settingsApp = Test_DataFactory.enableImportProcesses();
		Asunto__c theAsunto = Test_DataFactory.createOneAsuntoWithNumerosDeCredito();
		List<Numero_de_Credito__c> testNumerosDeCredito = [SELECT Id, Monto__c, Numero_de_Credito__c, Terceros_Obligados__c FROM Numero_de_Credito__c WHERE Asunto__c =: theAsunto.Id];
		Boolean montoSet = false;
		Boolean tercerosSet = false; 
		List<String> numerosDeCredito = theAsunto.NDC_Importe_Only__c.split(',');
		Set<String> numerosDeCreditoSet = new Set<String>(numerosDeCredito);
		for(Numero_de_Credito__c ndc : testNumerosDeCredito)
		{
			if(ndc.Monto__c == theAsunto.Monto_Importe_Only__c) montoSet = true;
			if(ndc.Terceros_Obligados__c == theAsunto.Deudores_Importe_Only__c) tercerosSet = true;
			if(!numerosDeCreditoSet.contains(ndc.Numero_de_Credito__c)) System.assert(false);
		}
		System.assert(montoSet);
		System.assert(tercerosSet);
	}

	@isTest static void should_create_etapa_judicial() {
		// Implement test code
		SECAL_App__c settingsApp = Test_DataFactory.enableImportProcesses();
		Asunto__c theAsunto = Test_DataFactory.createOneAsuntoWithEtapaJudicial(); 
		Etapa_Judicial__c theEtapa = [SELECT Id, Etapa_Judicial__c FROM Etapa_Judicial__c WHERE Asunto__c =: theAsunto.Id LIMIT 1];
		System.assertEquals(theEtapa.Etapa_Judicial__c, theAsunto.Etapa_Judicial_Importe_Only__c);
	}
	*/
}