unpackaged/main/default/objects/Asunto__c/Asunto__c.object-meta.xml
<CustomObject>
    <description>Listado de Asuntos</description>
    <label>Asunto</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Nombre de Asunto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asuntos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asunto__c/fields/Abogado_Externo__c.field-meta.xml
<CustomField>
    <fullName>Abogado_Externo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abogado Externo</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asuntos (Abogado Externo)</relationshipLabel>
    <relationshipName>Asuntos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Abogado_Interno__c.field-meta.xml
<CustomField>
    <fullName>Abogado_Interno__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Abogado Interno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asuntos</relationshipLabel>
    <relationshipName>Asuntos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Acreditado__c</fullName>
    <label>NOMBRE DEL DEMANDADO</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Deudores_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Deudores_Importe_Only__c</fullName>
    <label>Deudores Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor y localizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y emplazan por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Etapa_Judicial_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial_Importe_Only__c</fullName>
    <label>Etapa Judicial Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Fecha_de_Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Ingreso__c</fullName>
    <label>Fecha de Ingreso</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Monto_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>Monto_Importe_Only__c</fullName>
    <label>Monto Importe Only</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/NDC_Importe_Only__c.field-meta.xml
<CustomField>
    <fullName>NDC_Importe_Only__c</fullName>
    <label>NDC Importe Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asunto__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>Sucursal__c</referenceTo>
    <relationshipLabel>Asuntos</relationshipLabel>
    <relationshipName>Asuntos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/Etapa_Judicial__c.object-meta.xml
<CustomObject>
    <label>Etapa Judicial</label>
    <nameField>
        <displayFormat>EJ-{00000000}</displayFormat>
        <label>Nombre de Etapa Judicial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Etapas Judiciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <referenceTo>Asunto__c</referenceTo>
    <relationshipLabel>Etapas Judiciales</relationshipLabel>
    <relationshipName>Etapas_Judiciales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Codigo_de_Resultado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Resultado__c</fullName>
    <label>Código de Resultado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etapa_Judicial__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10 - Asignación a Externo</fullName>
                <label>10 - Enviada a Corresponsal</label>
            </value>
            <value>
                <fullName>AD - Rechazo de la demanda</fullName>
            </value>
            <value>
                <fullName>20 - Aclaración de la demanda</fullName>
                <label>20 - Presentada en Oficialía de Partes</label>
            </value>
            <value>
                <fullName>4A - Prevención para admisión de la demanda</fullName>
            </value>
            <value>
                <fullName>5A - Desahogo Prev. para admisión de demanda</fullName>
            </value>
            <value>
                <fullName>6A - Pendiente radicación de la demanda</fullName>
            </value>
            <value>
                <fullName>7A - Incompetencia del Juez</fullName>
            </value>
            <value>
                <fullName>8A - Demanda Admitida</fullName>
            </value>
            <value>
                <fullName>9A - Desechamiento de la de la demanda</fullName>
            </value>
            <value>
                <fullName>0A - Instructivo en Elaboración</fullName>
            </value>
            <value>
                <fullName>1B - Despecho / Exhorto Elabora y Presenta</fullName>
            </value>
            <value>
                <fullName>2B - Despacho / Exhorto Dilig. - Devolución</fullName>
            </value>
            <value>
                <fullName>3B - Desig. Actuario / Not. Encarga Actuario</fullName>
            </value>
            <value>
                <fullName>4B - Cita para Realizar Emplazamiento</fullName>
            </value>
            <value>
                <fullName>5B - Diligencia de Emplazamiento</fullName>
            </value>
            <value>
                <fullName>6B - Diligencia no Realizada</fullName>
            </value>
            <value>
                <fullName>7B - DNR por Inasistencia de Funcionario</fullName>
            </value>
            <value>
                <fullName>8B - DNR por no Encontrarse Persona Alguna</fullName>
            </value>
            <value>
                <fullName>9B - DNR por no ser Domicilio del Demandado</fullName>
            </value>
            <value>
                <fullName>0B - DNR por haber solo Menores de Edad</fullName>
            </value>
            <value>
                <fullName>30 - DNR por Negarse a Recibir Notificación</fullName>
            </value>
            <value>
                <fullName>40 - Emplazamiento Parcial</fullName>
            </value>
            <value>
                <fullName>3C - Autoriza Días/Horas Inhábil x Emplazar</fullName>
            </value>
            <value>
                <fullName>4C - Se Señala Nuevo Domicilio para Emplazar</fullName>
            </value>
            <value>
                <fullName>5C - Notificación y Emplazamiento Efectuado</fullName>
            </value>
            <value>
                <fullName>6C - Solicita Pesquisas Autoridades</fullName>
            </value>
            <value>
                <fullName>7C - Obtención de Oficios x Pesquisas</fullName>
            </value>
            <value>
                <fullName>8C - Presenta Oficios Pesquisas/se Razonan</fullName>
            </value>
            <value>
                <fullName>9C - Respuesta a Oficio de Localización</fullName>
            </value>
            <value>
                <fullName>0C - Ilocalizada No Emplazada / No Litis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Judicial__c</fullName>
    <label>Etapa Judicial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demanda</fullName>
            </value>
            <value>
                <fullName>Notificación y emplazamiento personal en trámite</fullName>
            </value>
            <value>
                <fullName>Deudor ilocalizado en emplazamiento</fullName>
            </value>
            <value>
                <fullName>Not. y Emplazam. por edictos en tramite</fullName>
            </value>
            <value>
                <fullName>Contestación a la demanda</fullName>
            </value>
            <value>
                <fullName>Embargo antes de Sentencia</fullName>
            </value>
            <value>
                <fullName>Pruebas</fullName>
            </value>
            <value>
                <fullName>Solicitud se dicte sentencia definitiva</fullName>
            </value>
            <value>
                <fullName>Apelación</fullName>
            </value>
            <value>
                <fullName>Amparo directo</fullName>
            </value>
            <value>
                <fullName>Ejecución de Sentencia</fullName>
            </value>
            <value>
                <fullName>Ejecución de Convenio</fullName>
            </value>
            <value>
                <fullName>Remate de Bienes</fullName>
            </value>
            <value>
                <fullName>Audiencia de Remate</fullName>
            </value>
            <value>
                <fullName>Escrituración en Trámite</fullName>
            </value>
            <value>
                <fullName>Toma posesión bien adjudicado y/o arrendado</fullName>
            </value>
            <value>
                <fullName>Incidente / Tercería</fullName>
            </value>
            <value>
                <fullName>Cierre de Juicio</fullName>
            </value>
            <value>
                <fullName>Para Dictamen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Etapa_Judicial__c/fields/Fecha_de_Etapa_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Etapa_Judicial__c</fullName>
    <label>Fecha de Etapa Judicial</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SECAL_App__c/SECAL_App__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SECAL App</label>
</CustomObject>

unpackaged/main/default/objects/SECAL_App__c/fields/Crear_Etapas_Judiciales_en_Importe__c.field-meta.xml
<CustomField>
    <fullName>Crear_Etapas_Judiciales_en_Importe__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activa la creacion automatica de etapas judiciales en importe</inlineHelpText>
    <label>Crear Etapas Judiciales en Importe</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SECAL_App__c/fields/Crear_Numeros_de_Credito_en_Importe__c.field-meta.xml
<CustomField>
    <fullName>Crear_Numeros_de_Credito_en_Importe__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activa la creacion automatica de numero de creditos en importe</inlineHelpText>
    <label>Crear Numeros de Credito en Importe</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Sucursal__c/Sucursal__c.object-meta.xml
<CustomObject>
    <label>Sucursal</label>
    <nameField>
        <label>Nombre de Sucursal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sucursal__c/fields/Ciudad2__c.field-meta.xml
<CustomField>
    <fullName>Ciudad2__c</fullName>
    <label>Ciudad</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Test_DataFactory.cls
public class Test_DataFactory {

	public static Contact createContact(String lastName)
	{
		Contact theContact = new Contact(LastName = lastName); 
		insert theContact;
		return theContact;
	}

	public static Sucursal__c createSucursal(String sucursalName)
	{
		Sucursal__c sucursal = new Sucursal__c(Name=sucursalName, Ciudad2__c = 'Monterrey');
		insert sucursal; 
		return sucursal;
	}

	public static Asunto__c createAsunto(Id sucursal, Id interno, Id externo)
	{
		Asunto__c theAsunto = Test_DataFactory.buildAsunto(sucursal, interno, externo);
		insert theAsunto; 
		return theAsunto;
	}

	public static Asunto__c buildAsunto(Id sucursal, Id interno, Id externo)
	{
		Asunto__c theAsunto = new Asunto__c();
		theAsunto.Fecha_de_Ingreso__c = System.today(); 
		theAsunto.Abogado_Interno__c = interno;
		theAsunto.Abogado_Externo__c = externo;
		theAsunto.Sucursal__c = sucursal;
		theAsunto.Acreditado__c = 'el acreditado';
		return theAsunto;
	}

	public static Asunto__c createOneAsunto()
	{
		Contact interno = Test_DataFactory.createContact('interno');
		Contact externo = Test_DataFactory.createContact('externo');
		Sucursal__c sucursal = Test_DataFactory.createSucursal('sucursal');
		Asunto__c asunto = Test_DataFactory.createAsunto(sucursal.Id, interno.Id, externo.Id);
		return asunto;
	}

	public static Asunto__c buildOneAsunto()
	{
		Contact interno = Test_DataFactory.createContact('interno');
		Contact externo = Test_DataFactory.createContact('externo');
		Sucursal__c sucursal = Test_DataFactory.createSucursal('sucursal');
		Asunto__c asunto = Test_DataFactory.buildAsunto(sucursal.Id, interno.Id, externo.Id);
		return asunto;
	}

	public static Asunto__c createOneAsuntoWithNumerosDeCredito()
	{
		Asunto__c theAsunto = Test_DataFactory.buildOneAsunto(); 
		theAsunto.Deudores_Importe_Only__c = 'deudores';
		theAsunto.Monto_Importe_Only__c = 1000;
		theAsunto.NDC_Importe_Only__c = '12345,67890';
		insert theAsunto;
		return theAsunto;
	}

	public static Asunto__c createOneAsuntoWithEtapaJudicial()
	{
		Asunto__c theAsunto = Test_DataFactory.buildOneAsunto(); 
		theAsunto.Etapa_Judicial_Importe_Only__c = 'Demanda';
		insert theAsunto;
		return theAsunto;
	}
	
	public static Etapa_Judicial__c createAsignacionAExternoEtapa(Id asuntoId)
	{
		Etapa_Judicial__c theEtapa = new Etapa_Judicial__c();
		theEtapa.Etapa_Judicial__c = 'Demanda';
		theEtapa.Codigo_de_Resultado__c = '10 - Asignación a Externo';
		theEtapa.Fecha_de_Etapa_Judicial__c = System.today();
		theEtapa.Asunto__c = asuntoId; 
		insert theEtapa;
		return theEtapa;
	}

	public static SECAL_App__c enableImportProcesses()
	{
		SECAL_App__c appSettings = new SECAL_App__c(); 
		appSettings.Crear_Numeros_de_Credito_en_Importe__c = true;
		appSettings.Crear_Etapas_Judiciales_en_Importe__c = true;
		insert appSettings;
		return appSettings;
	}
}